"""Add timestamp to posts

Revision ID: 36b34332ad89
Revises: 3c1f77744146
Create Date: 2025-03-18 20:52:10.085338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '36b34332ad89'
down_revision: Union[str, None] = '3c1f77744146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'time')
    # ### end Alembic commands ###
