"""Initial migration

Revision ID: dc5be18d3379
Revises: 
Create Date: 2025-03-14 18:16:24.695360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dc5be18d3379'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('role',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('name')
    )
    op.create_table('app_user',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role_uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['role_uid'], ['role.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('rolepermission',
    sa.Column('role_uid', sa.Uuid(), nullable=False),
    sa.Column('permission_uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_uid'], ['permission.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_uid'], ['role.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_uid', 'permission_uid')
    )
    op.create_table('post',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_uid'], ['app_user.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    op.drop_table('rolepermission')
    op.drop_table('app_user')
    op.drop_table('role')
    op.drop_table('permission')
    # ### end Alembic commands ###
